### ISSUE TITLE
Anchors on headlines

### ISSUE THREAD

**Issue by cschieder** [kubermatic/docs#1003]
every headline should 
- have a hover effect on the headline, making it a different color and have `copy to clipboard` tooltip appear
- have copy on click function 
- have an anchor built in that the link points to

**Comment by cschieder** [comment]
Hi Serg, can this be implemented?

**Comment by serg** [comment]
Hi @cschieder, please check this behaviour in [PR#1102](https://github.com/kubermatic/docs/pull/1102).
Demo: https://deploy-preview-1102--cranky-newton-4e6ed2.netlify.app/kubermatic/v2.20/

**Comment by cschieder** [comment]
Nice, can we make it say "copy link to section" instead?

**Comment by serg** [comment]
Done, @cschieder please check

**Comment by cschieder** [comment]
Copied to clipboard has the C capitalised and the copy link to section doesn't please make it consistent, either capitalize first letter or not


then it's good to go for me, thank you

**Comment by serg** [comment]
Ok, those were capitalized. Thank you!
