### ISSUE TITLE
Confusing Cluster Requirements Docs (worker port 10250)

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/docs#1095]
Our customer pointed out that the worker port requirement list contains ports 10250 and 10255 which seems to be unused after checking the code responsible for security group creation. 

Checking iptables on worker nodes proofs that kubelet seems to listen on a different ports than 10250 and 10255 (at least for ipv4).

**Acceptance criteria:** 
Clarify or remove confusing parts from the documentation.

Support issue: https://support.kubermatic.com/helpdesk/tickets/4088
Confusing documentation part (Worker Node(s)& User Cluster Worker Nodes table on the bottom): https://docs.kubermatic.com/kubermatic/v2.20/architecture/requirements/cluster_requirements/

**Comment by embik** [comment]
@pkprzekwas this is still relevant, no? Should it be reopened?

**Comment by WeirdMachine** [comment]
To clarify this port 10250 is defiantly used by kubelet and needs to be accessible in between worker nodes.

Some other ports like 10255 are not needed by KKP as we connect certain components via a Tunnel. 
This concept is nowhere documented nor explained and the list of required ports is just false in the sense that contains to much ports. 

It is also important to note that most ports are only required for internal access and should be blocked for public access.
