### ISSUE TITLE
Clarification about amount of possible seeds with CE

### ISSUE THREAD

**Issue by almereyda** [kubermatic/docs#1120]
This statement in the documentation for the v2.20 Kubermatic release implies, that there can be only one seed resource within the CE.

https://github.com/kubermatic/docs/blob/a83dec013ee395b4484c2f3072cb889ae3b33140/content/kubermatic/v2.20/installation/install_kkp_CE/add_seed_cluster_CE/_index.en.md?plain=1#L151-L152

This is due to the fact that a specific name can only be assigned once.

The overview of the installation instruction speaks about clusters in the plural before:

https://github.com/kubermatic/docs/blob/a83dec013ee395b4484c2f3072cb889ae3b33140/content/kubermatic/v2.20/installation/install_kkp_CE/add_seed_cluster_CE/_index.en.md?plain=1#L21

This might imply that it is possible to add more than one seed cluster. The architecture document and the images within it also suggests this.

Am I correct in concluding that the CE only allows a single seed cluster?

**Comment by embik** [comment]
Hey @almereyda, sorry this got closed due to inactivity. We added a note to the top of https://docs.kubermatic.com/kubermatic/main/installation/install-kkp-ce/add-seed-cluster-ce/ that mentions this more clearly. Does that fulfil your request adequately?

**Comment by almereyda** [comment]
Yes, many thanks! That seems to be precise enough.
