### ISSUE TITLE
Introduce Operating System Manager as a product/extension

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/docs#1182]
We would like to modify the products section and include OSM as well.

We added a temporary directory `_content` for the OSM documentation so that it's not rendered at the moment.

**Comment by ahmedwaleedmalik** [comment]
@cschieder @serg I've added the required documentation for OSM at https://github.com/kubermatic/docs/tree/master/_content/operatingsystemmanager. Now we need to plan, design, and modify the products list for our docs.

**Comment by cschieder** [comment]
We have a [draft](https://docs.google.com/document/d/1M5VFYziszLlKAN4YiJ165M34y2m11iM3F2H1RikkJt8/edit?usp=sharing) for changes relating to this already  cc @moadqassem

**Comment by serg** [comment]
I have added [some example](https://github.com/kubermatic/docs/pull/1192) about how we can use content pages without versioning. @cschieder, @moadqassem please have a look and let me know if this is what we would like to achieve?

**Comment by cschieder** [comment]
lgtm @serg

**Comment by ahmedwaleedmalik** [comment]
I think the only thing that we need to make a decision on is versioning. IMO this should have versions similar to KKP, KubeOne, and KubeCarrier. Since different versions of KKP and KubeOne can use different versions of OSM. But it could add a lot of maintenance overhead as well.

@moadqassem WDYT?

**Comment by ahmedwaleedmalik** [comment]
This is done now.
