### ISSUE TITLE
Broken link to docs.kubermatic.com in header navigation

### ISSUE THREAD

**Issue by embik** [kubermatic/docs#1442]
The header navigation menu ("Products" / "Services" / "Solutions") has a broken link to docs.kubermatic.com when you click "Resources" -> "Documentation".

It seems that's because of https://github.com/kubermatic/docs/blob/17d53cb0b13fa2c66b787ee406ab8c3686e3ee0b/data/mainMenu.yml#LL381C29-L381C29

Plus our template not being able to handle links like that (it only appends any link to `kubermatic.com`). I tried to figure this out by a quick glance but the header template looks quite complex.

**Comment by embik** [comment]
cc @serg

**Comment by serg** [comment]
@embik, we can remove this item from menu, because we already have top level link on the "Docs" homepage (at the left of the "Products" item). The corresponding [PR](https://github.com/kubermatic/docs/pull/1443) was created for this.

**Comment by embik** [comment]
@serg I went through some commits and it seemed we wanted to sync the navigation between main page and docs on purpose, wouldn't this kind of break that again since the link is there on kubermatic.com and not on docs.kubermatic.com? Fundamentally I agree, just curious about this bit.

**Comment by serg** [comment]
@embik, yeah we need to sync menu with main website, but additional settings is possible. Like in this case.
