### ISSUE TITLE
Add vsphere / cilium problematic network adapter information 

### ISSUE THREAD

**Issue by toschneck** [kubermatic/docs#1461]
Affected components
- KubeOne
- KKP
- Machine Controller / OSM

Currently, on the setup of Kubernetes clusters with Cilium we run into some problem, as we specified the `VMXNET3` network adapter in vSphere template, what's a known issue of cilium https://github.com/cilium/cilium/issues/21801#issuecomment-1588716630. 

The result was, that the Kubernetes Clusters overlay didn't come up with any good error why connectivity was broken or flaky. As this is very hard to debug, we need a proper warning around this in our vSphere setup docs.

Using the `Intel E1000E` network adapter **OR** adding the following commands to OSP / terraform seams to solve the problem. 
```bash
sudo ethtool -K ens192 tx-udp_tnl-segmentation off
sudo ethtool -K ens192 tx-udp_tnl-csum-segmentation off
```

Thanks @ahmedwaleedmalik and @WeirdMachine for finding ❤️ 

@csengerszabo 

Cross-Reference to more details:
https://kubermatic.slack.com/archives/C0512D6M7SB/p1685970431499839

**Comment by toschneck** [comment]
Nice, but I think we should backport this info to the current supported versions. 
And also mention it e.g. at this guide https://docs.kubermatic.com/kubeone/v1.6/guides/vsphere-template-vm/

**Comment by steled** [comment]
Hi,

see my comment at https://github.com/cilium/cilium/issues/21801#issuecomment-1761222143.
The configuration is not permanent, after reboot it's gone.
