### ISSUE TITLE
Cluster on Baremetal: taint is forbidden for clusters running Kubernetes 1.25+

### ISSUE THREAD

**Issue by hellt** [kubermatic/docs#1596]
Hi,
when using the manifest from https://docs.kubermatic.com/kubeone/v1.7/tutorials/creating-clusters-baremetal/ example, the following error is emitted:
```
❯ kubeone apply -m kubeone.yml 
Error: configuration validation
controlPlane.hosts.taints: Forbidden: "node-role.kubernetes.io/master" taint is forbidden for clusters running Kubernetes 1.25+
```

**Comment by Frisch12** [comment]
Issue is still present. 
Can someone please adjust the documentation?
