### ISSUE TITLE
Tables in CRD reference have broken rows on description line breaks

### ISSUE THREAD

**Issue by embik** [kubermatic/docs#1775]
It looks like something changed between KKP 2.25 and 2.26 (maybe some updates to controller-runtime or similar?) that broke our generated CRD reference. Look at https://docs.kubermatic.com/kubermatic/v2.26/references/crds/#applicationdefinitionspec, for example:

![Image](https://github.com/user-attachments/assets/9c2efbca-2ba0-42e6-954f-9f7f41b0c55d)

(Look at https://docs.kubermatic.com/kubermatic/v2.25/references/crds/#applicationdefinitionspec for how it's supposed to look like)

**Comment by xrstf** [comment]
For main branch this is already fixed.
