### ISSUE TITLE
Update Kubermatic Requirements

### ISSUE THREAD

**Issue by toschneck** [kubermatic/docs#230]
https://docs.loodse.com/kubermatic/master/requirements/cluster_requirements/
Page is pretty much outdated what is required.
This should also explain how a default setup looks like (kubeone + kubermatic)

The most important is here the Network Ranges, LB's, Firewalls, Certificates,  
as input you could take a look at: https://forms.gle/aLvRGfSApFejm5jQ7

**Comment by toschneck** [comment]
it should more now orientate at https://github.com/kubermatic/customer-projects/tree/master/components/setup-checklist

**Comment by shaase-ctrl** [comment]
This issue will tackle the on premise installation, we will cover hyperscaler installations in a seperat issue. 
A more rigid test is due to those requirements.

**Comment by toschneck** [comment]
Setup checklist with some more info's moved to: https://github.com/kubermatic-labs/community-components/tree/master/knowledge-base/setup-checklist

**Comment by toschneck** [comment]
still [requirements](https://docs.kubermatic.com/kubermatic/master/architecture/requirements/cluster_requirements/) are outdated and somehow in conflict with e.g. [Operating Systems Support Matrix](https://docs.kubermatic.com/kubermatic/master/architecture/requirements/support_policy/os_support_matrix/)
