### ISSUE TITLE
Document Setup and Usage of kubevirt CloudProvider

### ISSUE THREAD

**Issue by toschneck** [kubermatic/docs#269]
Besides this small readme we don't have any proper documentation how to use the kubevirt cloudprovider.
- https://github.com/kubermatic/machine-controller/blob/master/docs/kubevirt.md

- [ ] kubeconfig: seviceaccount + RBAC
- [ ] storage class requirements
- [ ] kubevirt operator version and pot. requirements to machine nodes
- [ ] machine spec options

For testing e.g. i used the following images
- Ubuntu Image URL for kubevirt: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
- CoreOS (uploaded to public gcloud bucket): https://storage.googleapis.com/ps-run/kubevirt/coreos/coreos_production_qemu_image.img

**Comment by moadqassem** [comment]
@toschneck All the points that were mentioned should be actually managed by the person who is installing KubeVirt no us. In other words, to achieve what you have mentioned you should follow the documentation of KubeVirt and they mention everything about what you need to install, thus those are not Kubermatic specific points. 

So here are some thoughts about the points you have mentioned: 
* `kubeconfig: seviceaccount + RBAC`
There are no special requirement for in regards to the kubeconfig except using the kubeconfig of the k8s cluster where kubevirt is installed. So if you are using the UI you should only enter the kubeconfig(base64 encoded) like all secrets and you are done.

* `storage class requirements`
This is also a specific thing to KubeVirt and at which infra it is installed with which CSI driver so it has nothing to do with KKP per se please follow this link from the kubevirt cdi docs https://github.com/kubevirt/containerized-data-importer/blob/master/doc/basic_pv_pvc_dv.md

* `kubevirt operator version and pot. requirements to machine nodes`
We can mentioned which operator version that was considered while working with kubevirt. Machine Nodes are also part of the Kubevirt Docs not KKP as they mention all these details and what has to be done. e.g nested virtualisation. For more info please refer to this link here: https://kubevirt.io/quickstart_cloud/

* `machine spec options` 
We already mention that in our documentation as we have an example and a testing sample that we run with our e2e tests:
https://github.com/kubermatic/machine-controller/blob/master/examples/kubevirt-machinedeployment.yaml
https://github.com/kubermatic/machine-controller/blob/master/test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml

* `For testing e.g. i used the following images` 
We also mention this in our docs, how to use the image repos, https://github.com/kubermatic/machine-controller/blob/master/docs/kubevirt.md#serving-supported-images

**Comment by toschneck** [comment]
@moadqassem you are potential right. But then we should at least mention like you did in your comment, what is needed to get started with kubevirt. A end user should have an as easy as possible start, currently you won't get even a starting point. That's why I think a reference and a little bit of explanation would be need at: https://docs.kubermatic.com/kubermatic/master/requirements/cloud_provider/
