### ISSUE TITLE
Document migration from v2.13 to v2.14

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/docs#381]
Document migration steps from v2.13 to v2.14. Particular care should be dedicated to the nodeport proxy that should move from Helm chart based installation to operator based.

**Comment by xrstf** [comment]
No, the nodeport-proxy is not considered stable in 2.14. We ship it in the operator, but it can be disabled and we haven't migrated ourselves. Also the cluster expose mechanism might change with your new SNI approach, so we would -- in worst case -- have to soon migrate again to something else.

**Comment by youssefazrak** [comment]
@xrstf didn't we agree on the fact that for new installations we use the operator? Legacy customers can still use the old chart that we keep in the tarballs.

**Comment by irozzo-1A** [comment]
@xrstf @youssefazrak Our current documentation relies on the operator to install the nodeport proxy, and I thought to understand that we are aligned on this.

> Also the cluster expose mechanism might change with your new SNI approach, so we would -- in worst case -- have to soon migrate again to something else.

This is another topic, even if it lands in 2.15 probably it will take some time before becoming GA

**Comment by xrstf** [comment]
@irozzo-1A would #447 fix this as well / do we still need this issue?

**Comment by irozzo-1A** [comment]
> @irozzo-1A would #447 fix this as well / do we still need this issue?

@xrstf I think we need it until we don't have proper 2.13 -> 2.14 docs. We can profit of the work we are doing to update this docs as well. But it would require dedicated testing.
