### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by scheeles** [kubermatic/docs#4]
Use the OpenAPI Spec and create a proper documentation for the API

Enhance the spec with more user content.

Let us use tools like
https://github.com/lord/slate 
https://github.com/Mermade/widdershins

**Comment by toschneck** [comment]
/remove-lifecycle stale
still usage of rest API is not documented in a good end user view

**Comment by moadqassem** [comment]
This ticket has been created since 3 years and I don't see any real activity attached to it. Closing!
