### ISSUE TITLE
Document the deprecation of `datacenters.yaml`

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/docs#401]
In Kubermatic `v2.15` we will deprecate datacenter configuration through `datacenters.yaml`, and then remove it entirely in Kubermatic `v2.16`.

For that purpose we must first update the documentation with the following:
- [ ] in docs master ensure that all documentation related to datacenters is based on CRDs and not `datacenters.yaml`
- [ ] ensure migration of Kubermatic installations from `datacenter.yaml` to CRD-based DCs is documented (if necessary)
- [ ] in docs master add warning boxes whenever datacenters are mentioned:
  - [ ] informing about the deprecation of `datacenter.yaml` in v2.15
  - [ ] informing about the removal of `datacenter.yaml` in v2.16
  - [ ] with a link to the migration guide

**Comment by irozzo-1A** [comment]
We should also check if the migration logic I removed here: https://github.com/kubermatic/kubermatic/pull/5683/files#diff-a0efc21a046c5d6f3b081f09300a0bf3L109 is still required or not.

**Comment by irozzo-1A** [comment]
ref: https://github.com/kubermatic/kubermatic/issues/5882
ref: https://github.com/kubermatic/kubermatic/issues/5734
