### ISSUE TITLE
Document required nodeports for seed cluster

### ISSUE THREAD

**Issue by xmulligan** [kubermatic/docs#409]
https://forum.kubermatic.com/t/ports-for-connecting-user-cluster-nodes-to-the-seed-control-plane/89/2

**Comment by youssefazrak** [comment]
@xmulligan is this a specific requirement for OpenStack + on-premise? 
By default, we provision a load balancer that exposes the required ports.

**Comment by xmulligan** [comment]
Not sure, this was a customer question while I was still at Kubermatic. Close it if the above info isn't enough because I don't have any more.
