### ISSUE TITLE
Add click to copy link function to headlines

### ISSUE THREAD

**Issue by cschieder** [kubermatic/docs#449]
### Why?
For ease of use, to copy accurate links to send to customers that jump precisely to the relevant topic.

### To do

- [ ] Add link icon with styling specified below

- [ ] Add copy link functionality

Note: Write me to recieve link icon svg, github doesn't like svgs, spacing left and right of icon: 10px
![docs-links](https://user-images.githubusercontent.com/49145827/93874117-2bb80280-fcd3-11ea-99eb-9ee91eb2c1bf.png)

**Comment by erdii** [comment]
this is already in the docs: https://docs.kubermatic.com/kubeone/v1.2/#easily-deploy-your-highly-available-cluster-on-any-infrastructure

**Comment by kron4eg** [comment]
@erdii thanks for noticing )
