### ISSUE TITLE
How to upgrade Kubermatic when custom addons images are used.

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/docs#451]
The goal of this issue is to describe the steps to follow when upgrading a KKP installation configured with custom addons images.

The issues that may arise are due to the fact than custom addons images are built on top of default addons images that are version specific and they do not seem to be always backward compatible. e.g. KKP 2.13 to 2.14

**Comment by xrstf** [comment]
Is there anything more than "bump your custom Docker image, build it, push it to your registry and then update KKP"?

> do not seem to be backward compatible

What exactly is not BC compatible? Does this refer to the big 2.14 cleanup where we for the first time documented the Go templating variables?

**Comment by irozzo-1A** [comment]
> Is there anything more than "bump your custom Docker image, build it, push it to your registry and then update KKP"?

Maybe, this issue is meant to define, test and document the procedure.

> What exactly is not BC compatible? Does this refer to the big 2.14 cleanup where we for the first time documented the Go templating variables?

What I observed is that was not possible to create new clusters after the upgrade, because some parameters required for the canal template were missing. I don't know the impact on existing clusters.

I observed this on a customer setup and I don't have the logs, but should not be difficult to reproduce.

**Comment by toschneck** [comment]
seams similar to https://github.com/kubermatic/kubermatic/issues/5153
