### ISSUE TITLE
Document etcd launcher usage and operational tasks

### ISSUE THREAD

**Issue by toschneck** [kubermatic/docs#459]
**User Story**
Due to the change to the new etcd launcher, it's also needed to document, how the launcher is working in detail. For issues like https://github.com/kubermatic/kubermatic/issues/6014 it's important to understand how the launcher is working, to debug or in best case fix problems. 

Additional to this the Operation pages under [Operation > etcd](https://docs.kubermatic.com/kubermatic/master/operation/etcd/) must be updated with this change.

**Acceptance criteria**
- changelog for potential migration use cases
- documentation about the etcd launcher concept / workflow
- operation documentation is updated

**Comment by moelsayed** [comment]
@toschneck Does this cover the requirement for this issue: https://docs.kubermatic.com/kubermatic/master/operation/etcd/etcd-launcher/, or you need additional information?

**Comment by toschneck** [comment]
LGTM
