### ISSUE TITLE
Document recent changes to the Terraform output for KubeOne example scripts

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/docs#496]
We should make sure that the documentation describing the KubeOne Terraform integration and the Terraform output for KubeOne example scripts is up to date.

For example, https://github.com/kubermatic/kubeone/pull/1174 added a new feature to the KubeOne Terraform integration, which was not documented.

**Comment by kron4eg** [comment]
Done in https://docs.kubermatic.com/kubeone/master/references/terraform_integration/
