### ISSUE TITLE
Document usage of cluster autoscaler for KubeOne and KKP

### ISSUE THREAD

**Issue by toschneck** [kubermatic/docs#501]
Currently the "how to use" and maybe some best practices are currently not visible for customers.

- At KKP, we don't have any description
- At KubeOne we only have this README, where users need to be aware that it's exists: https://github.com/kubermatic/kubeone/blob/master/addons/cluster-autoscaler/README.md

As this feature is really highlight in our stack, to do example cluster auto scaling on-premise, we should promote this more prominent.

**Comment by toschneck** [comment]
@PhillipAmend cloud you share your information of the latest setup?

**Comment by lsviben** [comment]
done through https://github.com/kubermatic/docs/pull/830
