### ISSUE TITLE
Create a comprehensive documentation for installing KKP 

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/docs#507]
As a user, I want to feel empowered by the documentation so that I am eager to install KKP on my own.

Thoughts & Criteria
- Find a way to display the same information at different sections but maintain only one block of information

- Rework all installation sections so that users are comfortable and motivated to proceed even with the more complexe KKP HA setup.
- Rearrange the structure, try to link as many interesting parts (even from external documentation) as comfortable
- Reflect the steps with infographics and give visual guidance throughout the process were the customer is in the installation process and what he needs to do
- Include new features and give advise what to do in which order (setup ha-cluster, install kkp, install seeds, install MLA, configure seeds, configure MLA, configure OPA etc.)

Section:
https://docs.kubermatic.com/kubermatic/v2.15/installation/
- Create a landing page within that section that includes the process overview as an infographic
- Show how many  steps are needed
- Create an index for the following sub-sections

Section:
https://docs.kubermatic.com/kubermatic/v2.15/installation/compatibility/
- Remove this from installation and create a Requirements & Compatibility section that is standalone
- Move all relevant content into this section
- Add a supported version matrix for all components
- Link official k8s documentation as well as other relevant docs in order to create an user oriented place to go

Section:
https://docs.kubermatic.com/kubermatic/v2.15/installation/monitoring_stack/
https://docs.kubermatic.com/kubermatic/v2.15/installation/logging_stack/
- Combine them and move everything into this section https://docs.kubermatic.com/kubermatic/v2.15/monitoring/
- Display and/or link needed information

**Comment by toschneck** [comment]
@themue created documentation concept a while go.
@themue can you share it with the people here
