### ISSUE TITLE
Test the upgrade from 2.15 to 2.16

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/docs#510]
As a user, I want only to go with a well tested upgrade so that I do not have any issues.

Acceptance Criteria
- Do the upgrade
- Test and document everything

**Comment by mfranczy** [comment]
I discovered some problems with KubeVirt cloud provider, but it's not about the upgrade mechanism itself (that works ok). 
Will come with upgrade tests plan in a new issue.
