### ISSUE TITLE
Docu - set nodeportrange for apiserver

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/docs#555]
**User Story**
As a user, I want to know about community contributed feautres updates as well.

https://github.com/kubermatic/kubermatic/pull/6533

**Acceptance criteria**
- document the feature so that other users are able to find it, learn from it and use it

**Comment by phiphi282** [comment]
Is there a certain location where I could add this documentation?
`EndpointReconcilingDisabled` is not documented either but would probably belong to the same place.
