### ISSUE TITLE
Link on Logo

### ISSUE THREAD

**Issue by cschieder** [kubermatic/docs#557]
link on the logo in the header redirects to kubermatic.com - I think it would be more intuitive if it sent you to the docs landing page instead, wdyt?

**Comment by cschieder** [comment]
also add "Documentation" to the header 
![image](https://user-images.githubusercontent.com/49145827/114392910-b3932a80-9b99-11eb-8156-2505eba11e7e.png)
Roboto, bold, 22px size

**Comment by cschieder** [comment]
@serg please implement this, just in case the question comes up: this change is only for the documentation, not for the website

**Comment by cschieder** [comment]
alternatively: add documentation text as shown and link to the docs.kubermatic.com on the "documentation" text, don't change link on logo in this case

**Comment by serg** [comment]
@cschieder here is also problem when explore the website on tight viewports. We have many menu items on main website.
I am afraid there is no space for "documentation" text. We need to think about this.
