### ISSUE TITLE
Document how to create a Kubernetes cluster on baremetal using KubeOne

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/docs#569]
This document targets users running on bare-metal and providers that are not officially supported. It should be based on the [Creating the Cluster](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) tutorial with the following changes:

- Downloading Terraform and Configuring Environment should be dropped
- References to machine-controller concepts (e.g. MachineDeployments) should be dropped
- The document should show how to create a `kubeone.yaml` file manually
  - Important bits: adding instances, adding static workers, API endpoint, setting cloud provider to `none`
- The document should mention infrastructure requirements
  - The [Infrastrucutre Management document](https://docs.kubermatic.com/kubeone/master/architecture/infrastructure_management/) can be used as a reference

**Comment by WeirdMachine** [comment]
https://github.com/kubermatic/docs/pull/694
