### ISSUE TITLE
Landing Page Redesign

### ISSUE THREAD

**Issue by cschieder** [kubermatic/docs#583]
Design: https://www.figma.com/file/Q7S2eEoTe3MXBWnwfVSvbe/DOCS?node-id=731%3A1
![Docs](https://user-images.githubusercontent.com/49145827/113867640-16a64b00-97af-11eb-9ff7-661775228e99.png)

### Effects
Hover on boxes: border turns teal, (hover and link should be on the whole box) `#00D9D2`

### Content
@shaase-ctrl please add what text should be used for the product documentation boxes

### Assets

Diagram image to be used:
<img width="1200" alt="KubermaticArchitecture 1" src="https://user-images.githubusercontent.com/49145827/113867723-30e02900-97af-11eb-9692-7489a7a7d861.png">

Logos sent via slack

Icons are here  https://drive.google.com/drive/u/1/folders/1Lir9GGcqk-Cd8MC2xdtZHKM88WqcYenY

Icon names are respectively, in order: (left side) Auto Scale, Statistik Up, Kubernetes || (right side) Time, Cash, Person

**Comment by shaase-ctrl** [comment]
We will draft the content here
https://docs.google.com/document/d/1ZNPfkz3lN8Z1CDfUBptM-IEMBsvMq59xEjDvjNX_HoE/edit

**Comment by serg** [comment]
@shaase-ctrl, thank you for content!
I checked the links, but it's following to not existing pages. I will hide Contribute section until we will have pages for this.
It will be easy to define link locations after and show this section.

**Comment by serg** [comment]
@shaase-ctrl do we need to create contribution pages also here? if do, we need to discuss with @cschieder how it should looks. Does this should look like inspiration example from your Google doc?
