### ISSUE TITLE
Switch KubeOne Graphic

### ISSUE THREAD

**Issue by cschieder** [kubermatic/docs#630]
https://docs.kubermatic.com/kubeone/v1.2/architecture/
<img width="842" alt="KubeOneArchitecture" src="https://user-images.githubusercontent.com/49145827/114390409-84c78500-9b96-11eb-99c8-0b80bff7674d.png">

**Comment by cschieder** [comment]
Would you take care of this, please? It's simply switching out one image, thank you! @fairhaven

**Comment by fairhaven** [comment]
Hi,
Alright

**Comment by cschieder** [comment]
I believe this was done
