### ISSUE TITLE
Add lines for sub levels of the navigation 

### ISSUE THREAD

**Issue by cschieder** [kubermatic/docs#663]
as shown, if there's more sublevels this pattern continues, another line and indent
![image](https://user-images.githubusercontent.com/49145827/115865147-39379580-a438-11eb-9804-a1b6aff478a7.png)

**Comment by cschieder** [comment]
cc @serg

**Comment by serg** [comment]
Hello @cschieder,
Should it looks like on this screenshot or exactly like on your image?
<img width="298" alt="Screenshot 2021-04-23 at 15 07 59" src="https://user-images.githubusercontent.com/1274660/115869064-04cad600-a446-11eb-9204-59e5e1366825.png">

**Comment by cschieder** [comment]
exactly like in the image, if possible

**Comment by serg** [comment]
@cschieder thank you for confirmation! I will look on what we can do with this.

**Comment by serg** [comment]
@cschieder this was added in https://github.com/kubermatic/docs/pull/668.
Please check behaviour for different cases on these pages:
- https://deploy-preview-668--cranky-newton-4e6ed2.netlify.app/kubermatic/v2.16/upgrading/2.14_to_2.15/
- https://deploy-preview-668--cranky-newton-4e6ed2.netlify.app/kubermatic/v2.16/requirements/cloud_provider/gcp/
- etc...

**Comment by cschieder** [comment]
Looks good to me! fyi for approval @kgroschoff :)
