### ISSUE TITLE
Switch order of search field and project dropdown

### ISSUE THREAD

**Issue by cschieder** [kubermatic/docs#664]
so it should look like this 
![image](https://user-images.githubusercontent.com/49145827/115865305-6dab5180-a438-11eb-80e0-89dd975055eb.png)

also please change "Kubermatic" to "KKP" in the dropdown

**Comment by cschieder** [comment]
cc @serg

**Comment by serg** [comment]
@cschieder do we need to follow the order for product dropdown like on homepage?
KubeOne
KKP
KubeCarrier

**Comment by cschieder** [comment]
Actually yes that would make sense!
