### ISSUE TITLE
Document how to get the recent used Defaults

### ISSUE THREAD

**Issue by toschneck** [kubermatic/docs#705]
On several Points in our docs, some defaults are managed, currently I'm not sure if they are 100% matching the current state. For me this is must have, so we need to ensure to provide an easy way to see the recent defaults, e.g. by a `docker run` command or a reference page, e.g. at the `references` section. 

In e.g. the Versioning package, the tool `docker run --rm quay.io/kubermatic/api:KUBERMATIC_VERSION kubermatic-operator-util defaults` is mentioned, what is NOT working anymore, this needs to get fixed. Doc page:
https://github.com/kubermatic/docs/blob/master/content/kubermatic/v2.17/tutorials_howtos/upgrading/version_and_upgrade_configuration/_index.en.md

Current defaults what needs to be easily accessible:
- `values.yaml`
- `KubermaticConfiguration`
- `Seed`
- `KubermaticSetting`
- Potential other Settings KKP Operators could need to modify:
```
k api-resources | grep -i kubermatic
addonconfigs                                       kubermatic.k8s.io/v1                   false        AddonConfig
addons                                             kubermatic.k8s.io/v1                   true         Addon
admissionplugins                                   kubermatic.k8s.io/v1                   false        AdmissionPlugin
clusters                           cl              kubermatic.k8s.io/v1                   false        Cluster
constraints                                        kubermatic.k8s.io/v1                   true         Constraint
constrainttemplates                                kubermatic.k8s.io/v1                   false        ConstraintTemplate
etcdbackupconfigs                                  kubermatic.k8s.io/v1                   true         EtcdBackupConfig
etcdrestores                                       kubermatic.k8s.io/v1                   true         EtcdRestore
externalclusters                   ecl             kubermatic.k8s.io/v1                   false        ExternalCluster
kubermaticsettings                                 kubermatic.k8s.io/v1                   false        KubermaticSetting
presets                                            kubermatic.k8s.io/v1                   false        Preset
projects                                           kubermatic.k8s.io/v1                   false        Project
seeds                                              kubermatic.k8s.io/v1                   true         Seed
userprojectbindings                                kubermatic.k8s.io/v1                   false        UserProjectBinding
users                                              kubermatic.k8s.io/v1                   false        User
usersshkeies                                       kubermatic.k8s.io/v1                   false        UserSSHKey
kubermaticconfigurations                           operator.kubermatic.io/v1alpha1        true         KubermaticConfiguration
```

**Comment by kron4eg** [comment]
@toschneck please check if https://docs.kubermatic.com/kubermatic/v2.17/tutorials_howtos/kkp_configuration/ fits the bill.

**Comment by toschneck** [comment]
@kron4eg
1. how get this page updated? If we change a default value, get it changed in the docs as well by automation?
2. What's about the other mentioned objects? How get their default values documentation get managed?

**Comment by kron4eg** [comment]
This page is autogenerated. Generation is launched from hack/update-docs.sh script, results can be seen at:
* https://github.com/kubermatic/kubermatic/blob/master/docs/zz_generated.addondata.go.txt
* https://github.com/kubermatic/kubermatic/blob/master/docs/zz_generated.kubermaticConfiguration.yaml
* https://github.com/kubermatic/kubermatic/blob/master/docs/zz_generated.seed.yaml

Once in a while someone copies those files to this repo.

**Comment by toschneck** [comment]
Ok so I think `Once in a while someone copies those files to this repo.` ist most issue here. As values changing and users don't know where to find the  real source of truth. I would suggest we do the following:
1. Add a link at the docu pages to the git repo generated version  so people can find it and potential can take a look in the version history
2. Add a copy job to the release CI, so we ensure that at least at every stable release the docs get updated.

Alternatively it would be potential also create to get this default values out of the `kubermatic-installer` command similar as the  `kubeone config print --full` command.

@kron4eg what do you think about?

**Comment by WeirdMachine** [comment]
As discussed in the daily, we are going to implement your suggestions.

**Comment by WeirdMachine** [comment]
Apparently the script mentioned by @kron4eg is actually syncing the generated files to the docs repo. However there are some links, that point to the wrong resource versions.

**Comment by toschneck** [comment]
@WeirdMachine  I don't get the last comment? So how are now the planes :sweat_smile:

**Comment by WeirdMachine** [comment]
I updated the documentation and there will be a print command for the KKP installer.
The docs get synced with KKP Repo for the Master but not for the Release versions.
