### ISSUE TITLE
Link to seed yaml site is broken on master and 2.17

### ISSUE THREAD

**Issue by stroebitzer** [kubermatic/docs#716]
On the page https://docs.kubermatic.com/kubermatic/master/guides/installation/add_seed_cluster_ce/

in the line 

> Refer to the Seed CRD documentation for a complete example of the Seed CustomResource and all possible datacenters.

the link is broken. In version 2.16 the link was set to https://docs.kubermatic.com/kubermatic/v2.16/concepts/seeds/

**Comment by kron4eg** [comment]
@stroebitzer We're gratefully accept contributions ;)
