### ISSUE TITLE
Update MLA diagrams

### ISSUE THREAD

**Issue by cschieder** [kubermatic/docs#790]
(afaik you guys are the MLA guys so that's why I'm pinging you :)) @rastislavs @jiachengxu @aborilov 
Please take a look at these updated diagrams, they're supposed to replace the ones found here:
https://docs.kubermatic.com/kubermatic/master/architecture/monitoring_logging_alerting/master_seed/
https://docs.kubermatic.com/kubermatic/master/architecture/monitoring_logging_alerting/user_cluster/

If there's nothing to change, it would be great if you could switch them out, thank you.

![MLA Master drawio](https://user-images.githubusercontent.com/49145827/132685783-65793358-c8ad-45a6-8fcf-588c41504b63.png)
![MLA-MLA Architecture drawio (2)](https://user-images.githubusercontent.com/49145827/132687248-b4baa468-a60d-493b-9a2a-d68fb5701618.png)

**Comment by jiachengxu** [comment]
Thanks @cschieder the new diagrams look great!
