### ISSUE TITLE
Improving the expose strategy documentation

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/docs#857]
Suggestion regarding the expose strategy documentation
Ticket# 10254 - erstellt 04.05.2021
Hello,
I am preparing the migration to the kubermatic-operator for our Kubermatic v2.15.11 installations according to
https://docs.kubermatic.com/kubermatic/v2.15/upgrading/2.14_to_2.15/chart_migration/

The documentation states "The proxy is still a required component of any Kubermatic setup [...]". I don't understand why nodeport-proxy should be a required component. We didn't need it yet. Our master and seed cluster is not running on a platform with LoadBalancer service support so we configured a DNS record with *.<<seed-cluster-name>>.base.domain pointing to a keepalived daemonset (we are planing to migrate to MetalLB) and hadn't issues with this for over 2 years.

So I have a suggestion regarding the expose strategy documentation.

We use NodePort as expose strategy without the nodeport-proxy Helm Chart e.g. we don't use nodeport-proxy but services of type NodePort directly exactly as stated in https://docs.kubermatic.com/kubermatic/v2.16/installation/add_seed_cluster_ee (but not in the v2.15 documentation...): "Depending on the chosen Expose Strategy, the control planes of all user clusters running in the Seed cluster will be exposed by the nodeport-proxy or using services of type NodePort directly.".

In https://docs.kubermatic.com/kubermatic/v2.15/concepts/expose-strategy/expose_strategy/ it is not clear which expose strategy is the default. According to https://docs.kubermatic.com/kubermatic/v2.15/concepts/kubermaticconfiguration/ the default is NodePort.
In the example Seed configuration https://docs.kubermatic.com/kubermatic/v2.15/concepts/seeds/ is this configuration block for the nodeport-proxy:

```
 # NodeportProxy can be used to configure the NodePort proxy service that is
 # responsible for making user-cluster control planes accessible from the outside.
 nodeport_proxy:
 [...]
   # Disable will prevent the KKP Operator from creating a nodeport-proxy
   # setup on the seed cluster. This should only be used if a suitable replacement
   # is installed (like the nodeport-proxy Helm chart).
   disable: false
```

This deploys the nodeport-proxy and tries to create a nodeport-proxy LoadBalancer service if the platform the seed is running on supports it. In conclusion the "Global LoadBalancer" expose strategy is used and not the base "Nodeport" strategy.

In https://docs.kubermatic.com/kubermatic/v2.17/guides/kkp_networking/expose_strategies/ you fixed several of this flaws.
But it is still unclear what has to be done if the platform the seed is running on does not support LoadBalancer services.
"[...] If services of type LoadBalancer are available all the services will be made available through a single load balancer, passing from the nodeport-proxy."

I would suggest to add a short explanation on how to archive this and adjust the configuration block in the seed example to state something like this:
```
 nodeport_proxy:
 [...]
   # Disable will prevent the KKP Operator from creating a nodeport-proxy
   # setup on the seed cluster. This should only be used if a suitable replacement
   # is in place (like the nodeport-proxy Helm chart or you are using services of
# type NodePort directly).
   disable: false
``` 

I would also appreciate if the yaml files in the examples directory of the releases would contain the same as the KubermaticConfiguration and Seed examples on the docs website.

**Comment by rastislavs** [comment]
Fixed in https://github.com/kubermatic/docs/pull/1049
