### ISSUE TITLE
KubeOne: TaintEffectNoSchedule is not getting removed using controlPlane.hosts config

### ISSUE THREAD

**Issue by archups** [kubermatic/docs#938]
While testing Single Master/Worker k8s Node setup with kubeone, used below kubeone config for controlPlane.hosts and executed command `kubectl apply -m kubeone.yaml -t ./terraform -v` The taint effect "NoSchedule" from control-plane/master node is not getting removed. 

`controlPlane:
  hosts:
    - publicAddress: "xx.xx.xx.xx"
      privateAddress: "xx.xx.xx.xx"
      hostname: "demo-cp-0"
      sshUsername: "xxxxx"
      taints: []
`

Looking for solution with k1 config.

**Comment by kron4eg** [comment]
@archups please omit using terraform integration (-t ./terraform).

**Comment by archups** [comment]
@kron4eg can you confirm if this is supported in Kubeone 1.3?

**Comment by kron4eg** [comment]
When terraform sourcing of information is used, the `controlPlane.hosts` part of the config is being overwritten by terraform integration.

I've created an issue to address this limitation in the future: https://github.com/kubermatic/kubeone/issues/1819.

**Comment by archups** [comment]
> When terraform sourcing of information is used, the `controlPlane.hosts` part of the config is being overwritten by terraform integration.
> 
> I've created an issue to address this limitation in the future: [kubermatic/kubeone#1819](https://github.com/kubermatic/kubeone/issues/1819).

Seems to be part of 1.5 kubeone release, so will wait until the release. Thank you @kron4eg for updates.
