### ISSUE TITLE
Search returns results from different versions

### ISSUE THREAD

**Issue by embik** [kubermatic/docs#981]
It looks like the search for docs.kubermatic.com has been updated recently (not sure when). Since then, searching for a key word gives you results from seemingly random KKP versions, not just the one I've selected. 

It's very hard to find the document I'm looking for in the right version.

Example:

![Screenshot 2022-02-18 at 14 10 21](https://user-images.githubusercontent.com/10295525/154688789-98d1541a-737c-4d83-93b3-f089a7966cff.png)

I would expect that the search prefers the version I have selected and maybe even omits the `master` version from searches if a stable release is selected

**Comment by embik** [comment]
@serg Is this something you could maybe look into?

**Comment by embik** [comment]
@KrissiWi this doesn't seem fixed yet, I'll reopen the ticket :-)

**Comment by dermorz** [comment]
I think this is related. The search results show mirrored hits from randomly sorted versions, but also not from v2.20 which is selected above.

![image](https://user-images.githubusercontent.com/682686/159425763-0c655471-5266-4bc4-9aa9-620c84db0771.png)

**Comment by serg** [comment]
I have uploaded search index manually for 2.20. At current moment search is working with all index nevertheless which product or version was selected. We will discuss about possibility of the improvements for this case.

**Comment by toschneck** [comment]
@serg it's a really annoying issue so we should try to fix it soon. Thanks for taking it forward.
